<a href="https://colab.research.google.com/github/pyaramsravanthi/AI-Assisted-Threat-Detection-Dashboard/blob/main/SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## SQL Prompts and Examples

In [1]:
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create a sample table: Employees
cursor.execute('''
CREATE TABLE employees (
    id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    department TEXT NOT NULL,
    salary INTEGER NOT NULL,
    hire_date DATE
);
''')

# Insert sample data
employees_data = [
    (1, 'Alice', 'Smith', 'HR', 60000, '2020-01-15'),
    (2, 'Bob', 'Johnson', 'Engineering', 85000, '2019-03-20'),
    (3, 'Charlie', 'Brown', 'HR', 62000, '2021-06-01'),
    (4, 'Diana', 'Prince', 'Marketing', 70000, '2018-11-10'),
    (5, 'Eve', 'Davis', 'Engineering', 90000, '2020-07-22'),
    (6, 'Frank', 'White', 'Sales', 75000, '2022-01-05'),
    (7, 'Grace', 'Black', 'Marketing', 72000, '2019-09-01'),
    (8, 'Heidi', 'Green', 'Sales', 78000, '2021-04-12'),
    (9, 'Ivan', 'Blue', 'Engineering', 95000, '2018-05-30'),
    (10, 'Judy', 'Red', 'HR', 61000, '2022-03-01')
]

cursor.executemany('INSERT INTO employees VALUES (?, ?, ?, ?, ?, ?)', employees_data)
conn.commit()

print("Sample 'employees' table created and populated successfully.")

Sample 'employees' table created and populated successfully.

### Prompt 1: Select all employees

In [2]:
# Query: Retrieve all columns and rows from the 'employees' table.
sql_query = "SELECT * FROM employees;"

df = pd.read_sql_query(sql_query, conn)
display(df)

   id first_name last_name   department  salary   hire_date
0   1      Alice     Smith           HR   60000  2020-01-15
1   2        Bob   Johnson  Engineering   85000  2019-03-20
2   3    Charlie     Brown           HR   62000  2021-06-01
3   4      Diana    Prince    Marketing   70000  2018-11-10
4   5        Eve     Davis  Engineering   90000  2020-07-22
5   6      Frank     White        Sales   75000  2022-01-05
6   7      Grace     Black    Marketing   72000  2019-09-01
7   8      Heidi     Green        Sales   78000  2021-04-12
8   9       Ivan      Blue  Engineering   95000  2018-05-30
9  10       Judy       Red           HR   61000  2022-03-01

### Prompt 2: Select employees from a specific department

In [3]:
# Query: Get the first name, last name, and salary of all employees in the 'Engineering' department.
sql_query = "SELECT first_name, last_name, salary FROM employees WHERE department = 'Engineering';"

df = pd.read_sql_query(sql_query, conn)
display(df)

  first_name last_name  salary
0        Bob   Johnson   85000
1        Eve     Davis   90000
2       Ivan      Blue   95000

### Prompt 3: Order employees by salary

In [4]:
# Query: List all employees, ordered by their salary in descending order.
sql_query = "SELECT * FROM employees ORDER BY salary DESC;"

df = pd.read_sql_query(sql_query, conn)
display(df)

   id first_name last_name   department  salary   hire_date
0   9       Ivan      Blue  Engineering   95000  2018-05-30
1   5        Eve     Davis  Engineering   90000  2020-07-22
2   2        Bob   Johnson  Engineering   85000  2019-03-20
3   8      Heidi     Green        Sales   78000  2021-04-12
4   6      Frank     White        Sales   75000  2022-01-05
5   7      Grace     Black    Marketing   72000  2019-09-01
6   4      Diana    Prince    Marketing   70000  2018-11-10
7   3    Charlie     Brown           HR   62000  2021-06-01
8  10       Judy       Red           HR   61000  2022-03-01
9   1      Alice     Smith           HR   60000  2020-01-15

### Prompt 4: Count employees per department

In [5]:
# Query: Find out how many employees are in each department.
sql_query = "SELECT department, COUNT(id) AS num_employees FROM employees GROUP BY department;"

df = pd.read_sql_query(sql_query, conn)
display(df)

    department  num_employees
0  Engineering              3
1           HR              3
2    Marketing              2
3        Sales              2

### Prompt 5: Calculate average salary per department

In [6]:
# Query: Calculate the average salary for each department.
sql_query = "SELECT department, AVG(salary) AS average_salary FROM employees GROUP BY department;"

df = pd.read_sql_query(sql_query, conn)
display(df)

    department  average_salary
0  Engineering         90000.0
1           HR         61000.0
2    Marketing         71000.0
3        Sales         76500.0

### Prompt 6: Find employees with salary above a certain amount

In [7]:
# Query: Get employees whose salary is greater than 70000.
sql_query = "SELECT first_name, last_name, salary FROM employees WHERE salary > 70000 ORDER BY salary DESC;"

df = pd.read_sql_query(sql_query, conn)
display(df)

  first_name last_name  salary
0       Ivan      Blue   95000
1        Eve     Davis   90000
2        Bob   Johnson   85000
3      Heidi     Green   78000
4      Frank     White   75000
5      Grace     Black   72000

### Prompt 7: Find employees hired after a specific date

In [8]:
# Query: Retrieve employees who were hired after '2020-01-01'.
sql_query = "SELECT first_name, last_name, hire_date FROM employees WHERE hire_date > '2020-01-01' ORDER BY hire_date ASC;"

df = pd.read_sql_query(sql_query, conn)
display(df)

  first_name last_name   hire_date
0      Alice     Smith  2020-01-15
1        Eve     Davis  2020-07-22
2      Heidi     Green  2021-04-12
3    Charlie     Brown  2021-06-01
4      Frank     White  2022-01-05
5       Judy       Red  2022-03-01

### Prompt 8: Find the highest salary in each department

In [9]:
# Query: Determine the maximum salary within each department.
sql_query = "SELECT department, MAX(salary) AS max_salary FROM employees GROUP BY department;"

df = pd.read_sql_query(sql_query, conn)
display(df)

    department  max_salary
0  Engineering       95000
1           HR       62000
2    Marketing       72000
3        Sales       78000

### Prompt 9: Employees whose names start with a specific letter

In [10]:
# Query: List all employees whose first name starts with 'A'.
sql_query = "SELECT first_name, last_name FROM employees WHERE first_name LIKE 'A%';"

df = pd.read_sql_query(sql_query, conn)
display(df)

  first_name last_name
0      Alice     Smith

### Prompt 10: Employees with salary within a range

In [11]:
# Query: Find employees with a salary between 60000 and 70000 (inclusive).
sql_query = "SELECT first_name, last_name, salary FROM employees WHERE salary BETWEEN 60000 AND 70000 ORDER BY salary;"

df = pd.read_sql_query(sql_query, conn)
display(df)

# Close the database connection
conn.close()

  first_name last_name  salary
0      Alice     Smith   60000
1       Judy       Red   61000
2    Charlie     Brown   62000
3      Diana    Prince   70000